;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-delete-forward
	c-electric-paren
	c-electric-semi&comma
	helm-mini
	indent-for-tab-command
	kill-region
	open-line-below
	org-beginning-of-line
	org-delete-char
	org-end-of-line
	org-yank
	yaml-electric-backspace
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	end-of-buffer
	mouse-set-region
	next-buffer
	open-line-above
	org-forward-sentence
	org-self-insert-command
	previous-buffer
	switch-to-buffer
	))
